name: Terraform Infra Deployment_updated

on:
  push:
    branches:
      - dev
      - preprod
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - preprod
          - prod

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.ref_name }}
      ENVIRONMENT: ${{ github.event.inputs.environment || (github.ref_name == 'main' && 'prod') || github.ref_name }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Environment
        run: |
          echo "Branch Name: $BRANCH_NAME"
          echo "Environment Selected: $ENVIRONMENT"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: 01.Modules/${{ env.ENVIRONMENT }}

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: 01.Modules/${{ env.ENVIRONMENT }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan.binary -var-file="terraform.tfvars"
        working-directory: 01.Modules/${{ env.ENVIRONMENT }}

      - name: Upload Plan Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            01.Modules/${{ env.ENVIRONMENT }}/tfplan.binary
            01.Modules/${{ env.ENVIRONMENT }}/.terraform.lock.hcl


  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment:
      name: ${{ github.event.inputs.environment || (github.ref_name == 'main' && 'prod') || github.ref_name }}

    env:
      BRANCH_NAME: ${{ github.ref_name }}
      ENVIRONMENT: ${{ github.event.inputs.environment || (github.ref_name == 'main' && 'prod') || github.ref_name }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Download Plan Artifacts
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: 01.Modules/${{ env.ENVIRONMENT }}

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: 01.Modules/${{ env.ENVIRONMENT }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan.binary
        working-directory: 01.Modules/${{ env.ENVIRONMENT }}